FROM golang:latest AS builder

WORKDIR /app

COPY go.mod .
# COPY go.sum .
RUN go mod download
COPY . .


# Build the Go server
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/tmp/main main.go

FROM alpine:latest


COPY --from=builder /app/tmp/main /app/server

CMD ["/app/server"]